// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqpantbzxedjhiobleuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxcGFudGJ6eGVkamhpb2JsZXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTEyODEsImV4cCI6MjA3MDI2NzI4MX0.0bigVt6ixoRkmxy4CWGEB3rkgebAE2DZm_Z4BRQ-Zh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});